export const presets = [
  {
    name: 'CLIP 1 — Alpis Fusion CRM Premium',
    durationSeconds: 40,
    url: 'https://laurandreea10.github.io/Alpis-Fusion-CRM-premium/',
    message: 'Produs profund: dashboard viu, command palette, CRM pipeline, bookings, facturare, automatizări.',
    viewport: { width: 1280, height: 720 },
    output: { encoder: 'libx264', crf: 18, fpsCapture: 30, fpsFinal: 24, canvasResolution: '1920x1080', outputResolution: '1280x720', preset: 'veryfast' },
    preRoll: [
      'Deschide URL-ul și așteaptă hero-ul cu animații.',
      'Dacă pornește turul ghidat: skip/close rapid.',
      'Asigură dashboard cu KPI-uri vizibile încă din primele secunde.'
    ],
    avoid: [
      'Nu comuta dark/light theme.',
      'Nu intra în Settings/Export.',
      'Nu scrie texte lungi în formulare.'
    ],
    shots: [
      { type: 'wait', ms: 3500, note: 'Dashboard idle, KPI + animații' },
      { type: 'clickOptional', selector: ['button', '[role="button"]', 'a'], textContains: ['Skip', 'Sari', 'Închide', 'Close'], timeoutMs: 1200 },
      { type: 'hover', selector: ['[data-kpi-card]', '.kpi-card', '.metric-card', '.card'], timeoutMs: 7000, note: 'Hover KPI' },
      { type: 'wait', ms: 1500 },
      { type: 'pressAny', keys: ['Control+K', 'Meta+K'], note: 'Command palette' },
      { type: 'wait', ms: 1000 },
      { type: 'type', selector: ['input[type="search"]', 'input', '[contenteditable="true"]'], text: 'clien', delay: 180 },
      { type: 'wait', ms: 700 },
      { type: 'press', keys: 'Enter' },
      { type: 'wait', ms: 2800 },
      { type: 'hover', selector: ['[data-client-row]', '.client-row', 'tbody tr', '.list-item'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: ['[data-client-row]', '.client-row', 'tbody tr', '.list-item'], timeoutMs: 7000 },
      { type: 'wait', ms: 2000 },
      { type: 'press', keys: 'Escape' },
      { type: 'wait', ms: 800 },
      { type: 'press', keys: 'P' },
      { type: 'wait', ms: 1800 },
      { type: 'drag', source: '[draggable="true"], .deal-card, .kanban-card', target: '.kanban-column:nth-child(2), [data-column="contacted"]', timeoutMs: 8000 },
      { type: 'wait', ms: 1400 },
      { type: 'press', keys: 'B' },
      { type: 'wait', ms: 1300 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['booking', 'Creează', 'Create'], timeoutMs: 7000 },
      { type: 'wait', ms: 1000 },
      { type: 'fillSmart', values: ['Demo Client', '25/05/2026', '10:00', 'Consultanță rapidă'] },
      { type: 'wait', ms: 1200 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['fact', 'invoice'], timeoutMs: 7000 },
      { type: 'wait', ms: 1200 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['Print', 'PDF'], timeoutMs: 7000 },
      { type: 'wait', ms: 1600 },
      { type: 'press', keys: 'Escape' },
      { type: 'wait', ms: 800 },
      { type: 'press', keys: 'A' },
      { type: 'wait', ms: 3000 },
      { type: 'scroll', pixels: -240, speedPxPerSecond: 180 }
    ]
  },
  {
    name: 'CLIP 2 — ClientFlow SaaS',
    durationSeconds: 30,
    url: 'https://laurandreea10.github.io/ClientFlow-SaaS-CRM-task-manager-automation-suite/',
    message: 'Mobile-first, rapid, cu tasks + calendar + clients + invoicing + availability + content studio într-un singur flux.',
    viewport: { width: 1280, height: 720 },
    output: { encoder: 'libx264', crf: 18, fpsCapture: 30, fpsFinal: 24, canvasResolution: '1920x1080', outputResolution: '1280x720', preset: 'veryfast' },
    preRoll: [
      'Deschide URL-ul în 1280x720.',
      'Asigură date demo (min 3 clienți, 5 task-uri).',
      'Plecăm din Dashboard.'
    ],
    avoid: [
      'Nu intra în Client Portal simulat.',
      'Nu scrie texte lungi în Content Studio.'
    ],
    shots: [
      { type: 'wait', ms: 3000, note: 'Dashboard intro' },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Tasks', 'Task'], timeoutMs: 7000 },
      { type: 'wait', ms: 1500 },
      { type: 'click', selector: ['button', '.status-badge', 'select'], timeoutMs: 7000 },
      { type: 'wait', ms: 1400 },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Calendar'], timeoutMs: 7000 },
      { type: 'wait', ms: 1600 },
      { type: 'hover', selector: ['.calendar-day', '[data-day]', 'td'], timeoutMs: 7000 },
      { type: 'wait', ms: 1400 },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Clients', 'Client'], timeoutMs: 7000 },
      { type: 'wait', ms: 1400 },
      { type: 'click', selector: ['[data-client-row]', '.client-row', 'tbody tr', '.list-item'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Invoic', 'Factur'], timeoutMs: 7000 },
      { type: 'wait', ms: 1400 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['Export PDF', 'PDF'], timeoutMs: 7000 },
      { type: 'wait', ms: 1600 },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Availability', 'Dispon'], timeoutMs: 7000 },
      { type: 'wait', ms: 1300 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['sample', 'Use sample'], timeoutMs: 7000 },
      { type: 'wait', ms: 1700 },
      { type: 'click', selector: ['a', 'button', '[role="tab"]'], textContains: ['Content', 'Studio'], timeoutMs: 7000 },
      { type: 'wait', ms: 1100 },
      { type: 'type', selector: ['textarea', 'input'], text: 'Idee: ofertă rapidă pentru lead-uri calde', delay: 80 },
      { type: 'wait', ms: 600 },
      { type: 'click', selector: ['button', '[role="button"]', 'label'], textContains: ['Instagram', 'LinkedIn'], timeoutMs: 7000 },
      { type: 'wait', ms: 700 },
      { type: 'click', selector: ['button', '[role="button"]'], textContains: ['Generează', 'Generate'], timeoutMs: 7000 },
      { type: 'wait', ms: 1600 },
      { type: 'click', selector: ['button', '[role="button"]', 'label'], textContains: ['EN', 'RO'], timeoutMs: 7000 },
      { type: 'wait', ms: 1500 }
    ]
  },
  {
    name: 'CLIP 3 — Alpis Impact Path',
    durationSeconds: 35,
    url: 'https://laurandreea10.github.io/ALPIS-ImpactPath/',
    message: 'Parcurs interactiv step-by-step: progres vizibil și CTA contextual la final.',
    viewport: { width: 1280, height: 720 },
    output: { encoder: 'libx264', crf: 18, fpsCapture: 30, fpsFinal: 24, canvasResolution: '1920x1080', outputResolution: '1280x720', preset: 'veryfast' },
    preRoll: [
      'Deschide demo-ul live.',
      'Resetează parcursul la pasul 1 din N (0%).',
      'Dacă există variantă statică, arată doar 2-3 secunde pentru contrast.'
    ],
    avoid: [
      'Nu scroll lung pe pagină statică.',
      'Nu sări peste pași.',
      'Nu adăuga subtitluri on-screen.'
    ],
    shots: [
      { type: 'wait', ms: 2500, note: 'Intro/contrast scurt' },
      { type: 'clickOptional', selector: ['button', '[role="button"]', 'a'], textContains: ['Start', 'Începe', 'Reset'], timeoutMs: 1600 },
      { type: 'wait', ms: 1300 },
      { type: 'click', selector: ['button', '[role="button"]', 'a'], textContains: ['Continuă', 'Continue', 'Next'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'clickOptional', selector: ['label', 'button', '[role="button"]', 'input[type="radio"] + *'], timeoutMs: 1300 },
      { type: 'wait', ms: 600 },
      { type: 'click', selector: ['button', '[role="button"]', 'a'], textContains: ['Continuă', 'Continue', 'Next'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'clickOptional', selector: ['button', '[role="button"]', '.option', '.choice'], timeoutMs: 1300 },
      { type: 'wait', ms: 700 },
      { type: 'click', selector: ['button', '[role="button"]', 'a'], textContains: ['Continuă', 'Continue', 'Next'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: ['button', '[role="button"]', 'a'], textContains: ['Continuă', 'Continue', 'Next'], timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: ['button', '[role="button"]', 'a'], textContains: ['CTA', 'Finalizează', 'Submit', 'Trimite', 'Get Started'], timeoutMs: 7000 },
      { type: 'wait', ms: 2200 }
    ]
  }
];
