export const presets = [
  {
    name: 'Alpis Fusion CRM Premium',
    durationSeconds: 40,
    url: 'https://laurandreea10.github.io/Alpis-Fusion-CRM-premium/',
    viewport: { width: 1280, height: 720 },
    output: {
      encoder: 'libx264',
      crf: 18,
      fpsCapture: 30,
      fpsFinal: 24,
      canvasResolution: '1920x1080',
      outputResolution: '1280x720'
    },
    shots: [
      { type: 'wait', ms: 4000, note: 'Dashboard idle' },
      { type: 'hover', selector: '[data-kpi-card], .kpi-card, .metric-card, .card', timeoutMs: 6000 },
      { type: 'wait', ms: 1200 },
      { type: 'press', keys: 'Control+K' },
      { type: 'wait', ms: 1200 },
      { type: 'type', selector: 'input, [contenteditable="true"]', text: 'clien', delay: 180 },
      { type: 'wait', ms: 900 },
      { type: 'press', keys: 'Enter' },
      { type: 'wait', ms: 4000 },
      { type: 'hover', selector: '[data-client-row], .client-row, tbody tr, .list-item', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: '[data-client-row], .client-row, tbody tr, .list-item', timeoutMs: 6000 },
      { type: 'wait', ms: 2200 },
      { type: 'press', keys: 'Escape' },
      { type: 'wait', ms: 900 },
      { type: 'press', keys: 'P' },
      { type: 'wait', ms: 1800 },
      { type: 'drag', source: '[draggable="true"], .deal-card, .kanban-card', target: '.kanban-column:nth-child(2), [data-column="contacted"]', timeoutMs: 7000 },
      { type: 'wait', ms: 1800 },
      { type: 'press', keys: 'B' },
      { type: 'wait', ms: 1500 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'booking', timeoutMs: 6000 },
      { type: 'wait', ms: 1200 },
      { type: 'fillSmart', values: ['Demo Client', '25/05/2026', '10:00', 'Consultanță'] },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'fact', timeoutMs: 6000 },
      { type: 'wait', ms: 1500 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'print', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'press', keys: 'Escape' },
      { type: 'wait', ms: 900 },
      { type: 'press', keys: 'A' },
      { type: 'wait', ms: 3200 },
      { type: 'scroll', pixels: -250, speedPxPerSecond: 180 }
    ]
  },
  {
    name: 'ClientFlow SaaS',
    durationSeconds: 30,
    url: 'https://laurandreea10.github.io/ClientFlow-SaaS-CRM-task-manager-automation-suite/',
    viewport: { width: 1280, height: 720 },
    output: {
      encoder: 'libx264',
      crf: 18,
      fpsCapture: 30,
      fpsFinal: 24,
      canvasResolution: '1920x1080',
      outputResolution: '1280x720'
    },
    shots: [
      { type: 'wait', ms: 3000 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Tasks', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: 'button, .status-badge, select', timeoutMs: 6000 },
      { type: 'wait', ms: 1600 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Calendar', timeoutMs: 6000 },
      { type: 'wait', ms: 2000 },
      { type: 'hover', selector: '.calendar-day, [data-day], td', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Clients', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: '[data-client-row], .client-row, tbody tr, .list-item', timeoutMs: 6000 },
      { type: 'wait', ms: 2200 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Invoic', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'Export PDF', timeoutMs: 6000 },
      { type: 'wait', ms: 2000 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Availability', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'sample', timeoutMs: 6000 },
      { type: 'wait', ms: 2200 },
      { type: 'click', selector: 'a, button, [role="tab"]', textContains: 'Content', timeoutMs: 6000 },
      { type: 'wait', ms: 1300 },
      { type: 'type', selector: 'textarea, input', text: 'Lansare ofertă mai simplă', delay: 100 },
      { type: 'wait', ms: 800 },
      { type: 'click', selector: 'button, [role="button"], label', textContains: 'LinkedIn', timeoutMs: 6000 },
      { type: 'wait', ms: 800 },
      { type: 'click', selector: 'button, [role="button"]', textContains: 'Gen', timeoutMs: 6000 },
      { type: 'wait', ms: 2200 },
      { type: 'click', selector: 'button, [role="button"], label', textContains: 'EN', timeoutMs: 6000 },
      { type: 'wait', ms: 1800 }
    ]
  }
];
